version: "3.9"

services:
  chat-service:
    build: .
    container_name: chat-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGODB_URI=${MONGODB_URI:-mongodb://localhost:27017/Chat-db}
      - MONGODB_DATABASE=Chat-db
    networks:
      - eciexpress-network

networks:
  eciexpress-network:
    driver: bridge